// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitaBookStrore.Models;

namespace VitaBookStrore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200706083019_CreatBookTabLe")]
    partial class CreatBookTabLe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VitaBookStrore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depscrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Remain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nguyễn Trí Đoàn- Nhã Uyên",
                            AvatarPath = "Để-con-được-ốm.jpg",
                            Depscrip = "Để con được ốm cùng với những câu chuyện nhỏ thú vị của người mẹ là lời khuyên mang tính chuyên môn, giải đáp cụ thể từ bác sỹ Nguyễn Trí Đoàn, giúp hóa giải những hiểu lầm từ kinh nghiệm dân gian được truyền lại, cũng như lý giải một cách khoa học những thông tin chưa đúng đắn đang được lưu truyền hiện nay, mang đến góc nhìn đúng đắn nhất cho mỗi hiện tượng, sự việc với những kiến thức y khoa hiện đại được cập nhật liên tục.",
                            GenreId = 2,
                            Name = "	Để con được ốm",
                            Price = 56000,
                            Remain = 0
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jessica Joelle Alexander - Iben Dissing Sandahl",
                            AvatarPath = "1888c2ad-68fd-41ed-a760-89aab2b2f7f2_ sach-nuoi-day-mot-dua-tre-hanh-phuc.jpg",
                            Depscrip = "Nuôi dạy một đứa trẻ hạnh phúc là cuốn cẩm nang dành cho cha mẹ đang có một trải nghiệm khó khăn, gian truân, nhưng cũng vui sướng và đầy viên mãn. Dù cho mọi người có đồng ý với mọi khía cạnh của kiểu Đan Mạch hay không, đây chắc chắn là một miếng trầu để mào đầu nhiều câu chuyện. Những ý tưởng này chính là hạt giống cho một phong trào đời thường và giúp nó phát triển thành những gì nó là ngày hôm nay.",
                            GenreId = 2,
                            Name = "Nuôi dạy một đứa trẻ hạnh phúc",
                            Price = 75000,
                            Remain = 0
                        });
                });

            modelBuilder.Entity("VitaBookStrore.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = " Sách kĩ năng"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = " Sách thiếu nhi"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = " Sách kinh doanh"
                        });
                });

            modelBuilder.Entity("VitaBookStrore.Models.Book", b =>
                {
                    b.HasOne("VitaBookStrore.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
